### ISSUE TITLE
Error module PIL.image

### ISSUE THREAD

**Issue by cpouchon** [Gene-Weaver/LeafMachine2#2]
Dear developers, 

I have followed your instructions to install LeafMachine2. 

Everything seems to be OK but now if I want to run the test.py file or to execute directly LeafMachine2 I have this issue: 

Traceback (most recent call last):
  File "/Users/pouchonc/LeafMachine2/LeafMachine2.py", line 1, in <module>
    from leafmachine2.machine.machine import machine
  File "/Users/pouchonc/LeafMachine2/leafmachine2/machine/machine.py", line 11, in <module>
    from leafmachine2.segmentation.detectron2.segment_leaves import segment_leaves
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/segment_leaves.py", line 26, in <module>
    from detector import Detector_LM2
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detector.py", line 4, in <module>
    from detectron2.utils.visualizer import Visualizer, ColorMode
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detectron2/utils/visualizer.py", line 16, in <module>
    from detectron2.data import MetadataCatalog
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detectron2/data/__init__.py", line 2, in <module>
    from . import transforms  # isort:skip
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detectron2/data/transforms/__init__.py", line 4, in <module>
    from .transform import *
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detectron2/data/transforms/transform.py", line 36, in <module>
    class ExtentTransform(Transform):
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detectron2/data/transforms/transform.py", line 46, in ExtentTransform
    def __init__(self, src_rect, output_size, interp=Image.LINEAR, fill=0):
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'

Have an idea? 

Thank you very much, 

Best regards, 

Charles

**Comment by Gene-Weaver** [comment]
The most recent version of PIL changed Image.LINEAR to Image.BILINEAR. We have incorporated this fix and are working to push an update soon. Thanks for reaching out!

**Comment by Gene-Weaver** [comment]
We have pushed an update that should resolve this issue. Please pull the changes and let us know if the problem persists.

**Comment by cpouchon** [comment]
Hi, thank you very much for your improve. 

I can now run the test.py file. 

However, I had to install "Pyexiv2" with pip, and now it crashed with this message: 

2023-09-21 09:21:37,329 - INFO - [BATCH 1 Convert Rulers] - Converting Rulers in batch 1 --- elapsed time: 864 seconds
2023-09-21 09:21:37,374 - INFO - [BATCH 1 Segment Leaves] - Segmenting leaves for batch 1 of 1
2023-09-21 09:21:37,904 - INFO - [BATCH 1 Segment Leaves] - Using Final Model: /Users/pouchonc/LeafMachine2/leafmachine2/segmentation/models/GroupB_Dataset_100000_Iter_1176PTS_512Batch_smooth_l1_LR00025_BGR/model_final.pth
Traceback (most recent call last):
  File "/Users/pouchonc/LeafMachine2/test.py", line 22, in <module>
    test_LM2()
  File "/Users/pouchonc/LeafMachine2/test.py", line 19, in test_LM2
    machine(cfg_file_path, dir_home, cfg_testing)
  File "/Users/pouchonc/LeafMachine2/leafmachine2/machine/machine.py", line 127, in machine
    Project = segment_leaves(cfg, logger, dir_home, Project, batch, n_batches, Dirs)
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/segment_leaves.py", line 49, in segment_leaves
    Instance_Detector_Whole = Detector_LM2(logger, dir_seg_model, cfg['leafmachine']['leaf_segmentation']['minimum_confidence_threshold'], 0)
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detector.py", line 86, in __init__
    self.predictor = PredictorLeaf(self.cfg)
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/predictor_leaf.py", line 11, in __init__
    self.model = build_model(self.cfg)
  File "/Users/pouchonc/LeafMachine2/leafmachine2/segmentation/detectron2/detectron2/modeling/meta_arch/build.py", line 23, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/Users/pouchonc/LeafMachine2/venv_LM2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Users/pouchonc/LeafMachine2/venv_LM2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/pouchonc/LeafMachine2/venv_LM2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/pouchonc/LeafMachine2/venv_LM2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Users/pouchonc/LeafMachine2/venv_LM2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Users/pouchonc/LeafMachine2/venv_LM2/lib/python3.9/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Thank you,
Charles

**Comment by Gene-Weaver** [comment]
Hello, the Pyexiv2 package (and a few other packages) were added to the requirements in the update. We recommend re-running the parts of the instructions that install packages into the virtual environment. 

With your new error, there are a few different potential causes.

1. Your computer does not have an Nvidia GPU. If this is the case, then parts of LeafMachine2 might not function correctly. Most of the machine learning algorithms can utilize the CPU, but the leaf segmentation algorithm has not been optimized to run only on the CPU as it takes about 10 times longer than running it on a GPU. I will work to add CPU support to the segmentation algorithm, but we still do not recommend using a CPU only.
2. PyTorch was not installed correctly. Please try running the command:
```{python}
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
```
To reinstall PyTorch. If this fails again (and you do have a GPU available), then it's likely that the CUDA version (we provide instructions for CUDA 11.3) does not match the PyTorch version. Please refer to the CUDA troubleshooting section for more information related to this type of error. If you have a GPU and it has a different CUDA version already installed, then you can visit the PyTorch website to determine which PyTorch version matches your CUDA version. We have not updated instructions for other versions yet, but we can confirm that LeafMachine2 will also work with CUDA 12.2 and the latest versions of PyTorch, version 2.X. 

You can check to see which version of CUDA is installed by opening a terminal and typing:
```{python}
nvidia-smi
```
If this command does not work, then CUDA is not installed and the LeafMachine2 error will persist until CUDA is installed.

I hope this helps, please let me know what you determine.
Thanks!
